"""feat: init

Revision ID: 21b9154339eb
Revises: 
Create Date: 2023-12-26 18:01:23.405889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '21b9154339eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_in_point',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pic', sa.VARCHAR(length=128), nullable=True),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('city_name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('point',
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('pic', sa.VARCHAR(length=128), nullable=True),
    sa.Column('stamp_id', sa.Integer(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_point_location', 'point', ['location'], unique=False, postgresql_using='gist')
    op.create_table('stamp',
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('pic', sa.VARCHAR(length=128), nullable=True),
    sa.Column('city_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stamp_location', 'stamp', ['location'], unique=False, postgresql_using='gist')
    op.create_table('user',
    sa.Column('user_name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('user_avatar', sa.VARCHAR(length=128), nullable=False),
    sa.Column('user_open_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index('idx_stamp_location', table_name='stamp', postgresql_using='gist')
    op.drop_table('stamp')
    op.drop_index('idx_point_location', table_name='point', postgresql_using='gist')
    op.drop_table('point')
    op.drop_table('feedback')
    op.drop_table('city')
    op.drop_table('check_in_point')
    # ### end Alembic commands ###
