"""feat: add latitude and longitude

Revision ID: e18bad332cf0
Revises: f162cfa2f3cb
Create Date: 2023-12-24 20:21:42.471637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18bad332cf0'
down_revision: Union[str, None] = 'f162cfa2f3cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True))
    op.add_column('point', sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point', 'longitude')
    op.drop_column('point', 'latitude')
    # ### end Alembic commands ###
