"""feat: add location for latitude and longitude

Revision ID: fc3fbd1788aa
Revises: e18bad332cf0
Create Date: 2023-12-24 21:18:41.086816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'fc3fbd1788aa'
down_revision: Union[str, None] = 'e18bad332cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point',
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('pic', sa.VARCHAR(length=128), nullable=True),
    sa.Column('stamp_id', sa.Integer(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_point_location', 'point', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_point_location', table_name='point', postgresql_using='gist')
    op.drop_table('point')
    # ### end Alembic commands ###
